# Generated by Django 4.1.6 on 2023-02-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeniero',
            name='Username',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
